### ISSUE TITLE
[RFE] Tag should be an array?

### ISSUE THREAD

**Issue by shabazzfsher** [rancherfederal/rancher-cluster-templates#14]
#Feature Request

Request description:
Customer requests that tag field should be an array? (Not 100% on this one but would make sense, need to check the spec of vmwarevsphereconfig to be sure)

**Comment by bcdurden** [comment]
The tag field is an array. The helm chart does not enforce this but the Rancher CRD does.
```console
>kubectl explain VmwarevsphereConfig.tag
GROUP:      rke-machine-config.cattle.io
KIND:       VmwarevsphereConfig
VERSION:    v1

FIELD: tag <[]string>

DESCRIPTION:
    vSphere tag id e.g. urn:xxx
```

**Comment by zlmitchell** [comment]
@bcdurden Did you check the helmchart before closing this. You're killing me Brian.
Yes the API is an array, the helmchart only allows a single value. The helmchart needs to be updated to allow an array in the values.yaml and be received in the following file

https://github.com/rancherfederal/rancher-cluster-templates/blob/main/charts/cluster-templates/templates/nodeconfig-vsphere.yaml#L40

**Comment by zlmitchell** [comment]
@zackbradys can you reopen this.
