### ISSUE TITLE
Feature Request: Enable Support for Additional Manifests in RKEConfig for Out-of-Tree Provider Integration

### ISSUE THREAD

**Issue by shabazzfsher** [rancherfederal/rancher-cluster-templates#21]
#Feature Request
Customer needs the ability to add additionalManifests to the helm chart as this is the glue to work with out-of-tree providers (aws, vsphere). 

```
spec:
  rkeConfig:
    additionalManifest: |-
 ```
Additional notes:
Here is a link to the rancher doc on this specific use case https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/set-up-cloud-providers/amazon#using-the-out-of-tree-aws-cloud-provider

**Comment by zackbradys** [comment]
Closing as resolved per PR https://github.com/rancherfederal/rancher-cluster-templates/pull/22!
