### ISSUE TITLE
Running into YAML to JSON conversion issues

### ISSUE THREAD

**Issue by jhkang-esnet** [rancherfederal/rancher-cluster-templates#30]
Hey Rancher Federal,

I've added this repo to an MCM cluster hosted on AWS using Rancher provided TF templates and I run into this issue. I've been looking at the nodeconfig-aws YAML file and I can't find what's wrong with it. Any thoughts?

helm install --generate-name=true --namespace=fleet-default --timeout=10m0s --values=/home/shell/helm/values-rancher-cluster-templates-0.5.3.yaml --version=0.5.3 --wait=true /home/shell/helm/rancher-cluster-templates-0.5.3.tgz
2024-10-16T14:11:14.299341585Z Error: INSTALLATION FAILED: YAML parse error on rancher-cluster-templates/templates/nodeconfig-aws.yaml: error converting YAML to JSON: yaml: line 12: could not find expected ':'

**Comment by zackbradys** [comment]
Hey @jhkang-esnet, are you able to share your values so we can troubleshoot this?

**Comment by zackbradys** [comment]
please reopen this issue if you are still encountering this issue!
