### ISSUE TITLE
CloudCred expects Rancher generated name instead of user friendly name

### ISSUE THREAD

**Issue by andrew-morris-rgs** [rancherfederal/rancher-cluster-templates#39]
For example `cc-1234k` instead `andy-amazon`. A customer and I would prefer to point to the user friendly name.

**Comment by zackbradys** [comment]
Hey @andrew-morris-rgs, you can already do this today!

Instructions here... https://github.com/rancherfederal/rancher-cluster-templates/tree/main/charts/cluster-templates#chartcluster-secrets-management

---

https://github.com/rancherfederal/rancher-cluster-templates/blob/a8406f168ef8bd1aa43c99f69774a3550d0fd40c/charts/cluster-templates/values.yaml#L8

**Comment by andrew-morris-rgs** [comment]
I will try it again with the annotations added
